# .github/workflows/main.yml
name: Example
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: upload-to-gdrive
        uses: team-tumbleweed/gdrive-upload-action@development
        with:
          filename: 'main.go'
          parentId: ${{ secrets.parentId }}
          credentials: ${{ secrets.credentials }}
