# .github/workflows/main.yml
name: Example
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Mask fruit
        uses: Mathisco-01/ghub-actions-test@master
        with:
          name: mathis

      - name: Echo name
        run: echo "test mathis test"
